// Generated by gencpp from file hector_nav_msgs/GetDistanceToObstacle.msg
// DO NOT EDIT!


#ifndef HECTOR_NAV_MSGS_MESSAGE_GETDISTANCETOOBSTACLE_H
#define HECTOR_NAV_MSGS_MESSAGE_GETDISTANCETOOBSTACLE_H

#include <ros/service_traits.h>


#include <hector_nav_msgs/GetDistanceToObstacleRequest.h>
#include <hector_nav_msgs/GetDistanceToObstacleResponse.h>


namespace hector_nav_msgs
{

struct GetDistanceToObstacle
{

typedef GetDistanceToObstacleRequest Request;
typedef GetDistanceToObstacleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetDistanceToObstacle
} // namespace hector_nav_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hector_nav_msgs::GetDistanceToObstacle > {
  static const char* value()
  {
    return "db18115f41079cd33136cf1e23b216ad";
  }

  static const char* value(const ::hector_nav_msgs::GetDistanceToObstacle&) { return value(); }
};

template<>
struct DataType< ::hector_nav_msgs::GetDistanceToObstacle > {
  static const char* value()
  {
    return "hector_nav_msgs/GetDistanceToObstacle";
  }

  static const char* value(const ::hector_nav_msgs::GetDistanceToObstacle&) { return value(); }
};


// service_traits::MD5Sum< ::hector_nav_msgs::GetDistanceToObstacleRequest> should match 
// service_traits::MD5Sum< ::hector_nav_msgs::GetDistanceToObstacle > 
template<>
struct MD5Sum< ::hector_nav_msgs::GetDistanceToObstacleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hector_nav_msgs::GetDistanceToObstacle >::value();
  }
  static const char* value(const ::hector_nav_msgs::GetDistanceToObstacleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hector_nav_msgs::GetDistanceToObstacleRequest> should match 
// service_traits::DataType< ::hector_nav_msgs::GetDistanceToObstacle > 
template<>
struct DataType< ::hector_nav_msgs::GetDistanceToObstacleRequest>
{
  static const char* value()
  {
    return DataType< ::hector_nav_msgs::GetDistanceToObstacle >::value();
  }
  static const char* value(const ::hector_nav_msgs::GetDistanceToObstacleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hector_nav_msgs::GetDistanceToObstacleResponse> should match 
// service_traits::MD5Sum< ::hector_nav_msgs::GetDistanceToObstacle > 
template<>
struct MD5Sum< ::hector_nav_msgs::GetDistanceToObstacleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hector_nav_msgs::GetDistanceToObstacle >::value();
  }
  static const char* value(const ::hector_nav_msgs::GetDistanceToObstacleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hector_nav_msgs::GetDistanceToObstacleResponse> should match 
// service_traits::DataType< ::hector_nav_msgs::GetDistanceToObstacle > 
template<>
struct DataType< ::hector_nav_msgs::GetDistanceToObstacleResponse>
{
  static const char* value()
  {
    return DataType< ::hector_nav_msgs::GetDistanceToObstacle >::value();
  }
  static const char* value(const ::hector_nav_msgs::GetDistanceToObstacleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HECTOR_NAV_MSGS_MESSAGE_GETDISTANCETOOBSTACLE_H
