// Generated by gencpp from file hector_nav_msgs/GetNormal.msg
// DO NOT EDIT!


#ifndef HECTOR_NAV_MSGS_MESSAGE_GETNORMAL_H
#define HECTOR_NAV_MSGS_MESSAGE_GETNORMAL_H

#include <ros/service_traits.h>


#include <hector_nav_msgs/GetNormalRequest.h>
#include <hector_nav_msgs/GetNormalResponse.h>


namespace hector_nav_msgs
{

struct GetNormal
{

typedef GetNormalRequest Request;
typedef GetNormalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetNormal
} // namespace hector_nav_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hector_nav_msgs::GetNormal > {
  static const char* value()
  {
    return "134adf3dd9201d61a4857acd73cf22f6";
  }

  static const char* value(const ::hector_nav_msgs::GetNormal&) { return value(); }
};

template<>
struct DataType< ::hector_nav_msgs::GetNormal > {
  static const char* value()
  {
    return "hector_nav_msgs/GetNormal";
  }

  static const char* value(const ::hector_nav_msgs::GetNormal&) { return value(); }
};


// service_traits::MD5Sum< ::hector_nav_msgs::GetNormalRequest> should match 
// service_traits::MD5Sum< ::hector_nav_msgs::GetNormal > 
template<>
struct MD5Sum< ::hector_nav_msgs::GetNormalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hector_nav_msgs::GetNormal >::value();
  }
  static const char* value(const ::hector_nav_msgs::GetNormalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hector_nav_msgs::GetNormalRequest> should match 
// service_traits::DataType< ::hector_nav_msgs::GetNormal > 
template<>
struct DataType< ::hector_nav_msgs::GetNormalRequest>
{
  static const char* value()
  {
    return DataType< ::hector_nav_msgs::GetNormal >::value();
  }
  static const char* value(const ::hector_nav_msgs::GetNormalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hector_nav_msgs::GetNormalResponse> should match 
// service_traits::MD5Sum< ::hector_nav_msgs::GetNormal > 
template<>
struct MD5Sum< ::hector_nav_msgs::GetNormalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hector_nav_msgs::GetNormal >::value();
  }
  static const char* value(const ::hector_nav_msgs::GetNormalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hector_nav_msgs::GetNormalResponse> should match 
// service_traits::DataType< ::hector_nav_msgs::GetNormal > 
template<>
struct DataType< ::hector_nav_msgs::GetNormalResponse>
{
  static const char* value()
  {
    return DataType< ::hector_nav_msgs::GetNormal >::value();
  }
  static const char* value(const ::hector_nav_msgs::GetNormalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HECTOR_NAV_MSGS_MESSAGE_GETNORMAL_H
