// Generated by gencpp from file hector_nav_msgs/GetSearchPosition.msg
// DO NOT EDIT!


#ifndef HECTOR_NAV_MSGS_MESSAGE_GETSEARCHPOSITION_H
#define HECTOR_NAV_MSGS_MESSAGE_GETSEARCHPOSITION_H

#include <ros/service_traits.h>


#include <hector_nav_msgs/GetSearchPositionRequest.h>
#include <hector_nav_msgs/GetSearchPositionResponse.h>


namespace hector_nav_msgs
{

struct GetSearchPosition
{

typedef GetSearchPositionRequest Request;
typedef GetSearchPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSearchPosition
} // namespace hector_nav_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hector_nav_msgs::GetSearchPosition > {
  static const char* value()
  {
    return "a28d7c2840927c12082b304156df4111";
  }

  static const char* value(const ::hector_nav_msgs::GetSearchPosition&) { return value(); }
};

template<>
struct DataType< ::hector_nav_msgs::GetSearchPosition > {
  static const char* value()
  {
    return "hector_nav_msgs/GetSearchPosition";
  }

  static const char* value(const ::hector_nav_msgs::GetSearchPosition&) { return value(); }
};


// service_traits::MD5Sum< ::hector_nav_msgs::GetSearchPositionRequest> should match 
// service_traits::MD5Sum< ::hector_nav_msgs::GetSearchPosition > 
template<>
struct MD5Sum< ::hector_nav_msgs::GetSearchPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hector_nav_msgs::GetSearchPosition >::value();
  }
  static const char* value(const ::hector_nav_msgs::GetSearchPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hector_nav_msgs::GetSearchPositionRequest> should match 
// service_traits::DataType< ::hector_nav_msgs::GetSearchPosition > 
template<>
struct DataType< ::hector_nav_msgs::GetSearchPositionRequest>
{
  static const char* value()
  {
    return DataType< ::hector_nav_msgs::GetSearchPosition >::value();
  }
  static const char* value(const ::hector_nav_msgs::GetSearchPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hector_nav_msgs::GetSearchPositionResponse> should match 
// service_traits::MD5Sum< ::hector_nav_msgs::GetSearchPosition > 
template<>
struct MD5Sum< ::hector_nav_msgs::GetSearchPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hector_nav_msgs::GetSearchPosition >::value();
  }
  static const char* value(const ::hector_nav_msgs::GetSearchPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hector_nav_msgs::GetSearchPositionResponse> should match 
// service_traits::DataType< ::hector_nav_msgs::GetSearchPosition > 
template<>
struct DataType< ::hector_nav_msgs::GetSearchPositionResponse>
{
  static const char* value()
  {
    return DataType< ::hector_nav_msgs::GetSearchPosition >::value();
  }
  static const char* value(const ::hector_nav_msgs::GetSearchPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HECTOR_NAV_MSGS_MESSAGE_GETSEARCHPOSITION_H
