; Auto-generated. Do not edit!


(cl:in-package teleop_tools_msgs-msg)


;//! \htmlinclude IncrementFeedback.msg.html

(cl:defclass <IncrementFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass IncrementFeedback (<IncrementFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <IncrementFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'IncrementFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name teleop_tools_msgs-msg:<IncrementFeedback> is deprecated: use teleop_tools_msgs-msg:IncrementFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <IncrementFeedback>) ostream)
  "Serializes a message object of type '<IncrementFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <IncrementFeedback>) istream)
  "Deserializes a message object of type '<IncrementFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<IncrementFeedback>)))
  "Returns string type for a message object of type '<IncrementFeedback>"
  "teleop_tools_msgs/IncrementFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'IncrementFeedback)))
  "Returns string type for a message object of type 'IncrementFeedback"
  "teleop_tools_msgs/IncrementFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<IncrementFeedback>)))
  "Returns md5sum for a message object of type '<IncrementFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'IncrementFeedback)))
  "Returns md5sum for a message object of type 'IncrementFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<IncrementFeedback>)))
  "Returns full string definition for message of type '<IncrementFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'IncrementFeedback)))
  "Returns full string definition for message of type 'IncrementFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <IncrementFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <IncrementFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'IncrementFeedback
))
