; Auto-generated. Do not edit!


(cl:in-package teleop_tools_msgs-msg)


;//! \htmlinclude IncrementGoal.msg.html

(cl:defclass <IncrementGoal> (roslisp-msg-protocol:ros-message)
  ((increment_by
    :reader increment_by
    :initarg :increment_by
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass IncrementGoal (<IncrementGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <IncrementGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'IncrementGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name teleop_tools_msgs-msg:<IncrementGoal> is deprecated: use teleop_tools_msgs-msg:IncrementGoal instead.")))

(cl:ensure-generic-function 'increment_by-val :lambda-list '(m))
(cl:defmethod increment_by-val ((m <IncrementGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader teleop_tools_msgs-msg:increment_by-val is deprecated.  Use teleop_tools_msgs-msg:increment_by instead.")
  (increment_by m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <IncrementGoal>) ostream)
  "Serializes a message object of type '<IncrementGoal>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'increment_by))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'increment_by))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <IncrementGoal>) istream)
  "Deserializes a message object of type '<IncrementGoal>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'increment_by) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'increment_by)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<IncrementGoal>)))
  "Returns string type for a message object of type '<IncrementGoal>"
  "teleop_tools_msgs/IncrementGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'IncrementGoal)))
  "Returns string type for a message object of type 'IncrementGoal"
  "teleop_tools_msgs/IncrementGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<IncrementGoal>)))
  "Returns md5sum for a message object of type '<IncrementGoal>"
  "6801194f49dae2bee5b8f17b6ce4596f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'IncrementGoal)))
  "Returns md5sum for a message object of type 'IncrementGoal"
  "6801194f49dae2bee5b8f17b6ce4596f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<IncrementGoal>)))
  "Returns full string definition for message of type '<IncrementGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32[] increment_by~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'IncrementGoal)))
  "Returns full string definition for message of type 'IncrementGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32[] increment_by~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <IncrementGoal>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'increment_by) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <IncrementGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'IncrementGoal
    (cl:cons ':increment_by (increment_by msg))
))
