; Auto-generated. Do not edit!


(cl:in-package teleop_tools_msgs-msg)


;//! \htmlinclude IncrementActionGoal.msg.html

(cl:defclass <IncrementActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type teleop_tools_msgs-msg:IncrementGoal
    :initform (cl:make-instance 'teleop_tools_msgs-msg:IncrementGoal)))
)

(cl:defclass IncrementActionGoal (<IncrementActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <IncrementActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'IncrementActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name teleop_tools_msgs-msg:<IncrementActionGoal> is deprecated: use teleop_tools_msgs-msg:IncrementActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <IncrementActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader teleop_tools_msgs-msg:header-val is deprecated.  Use teleop_tools_msgs-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <IncrementActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader teleop_tools_msgs-msg:goal_id-val is deprecated.  Use teleop_tools_msgs-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <IncrementActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader teleop_tools_msgs-msg:goal-val is deprecated.  Use teleop_tools_msgs-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <IncrementActionGoal>) ostream)
  "Serializes a message object of type '<IncrementActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <IncrementActionGoal>) istream)
  "Deserializes a message object of type '<IncrementActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<IncrementActionGoal>)))
  "Returns string type for a message object of type '<IncrementActionGoal>"
  "teleop_tools_msgs/IncrementActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'IncrementActionGoal)))
  "Returns string type for a message object of type 'IncrementActionGoal"
  "teleop_tools_msgs/IncrementActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<IncrementActionGoal>)))
  "Returns md5sum for a message object of type '<IncrementActionGoal>"
  "fd0f65b046bd08324be539043a8c21f7")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'IncrementActionGoal)))
  "Returns md5sum for a message object of type 'IncrementActionGoal"
  "fd0f65b046bd08324be539043a8c21f7")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<IncrementActionGoal>)))
  "Returns full string definition for message of type '<IncrementActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%IncrementGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: teleop_tools_msgs/IncrementGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32[] increment_by~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'IncrementActionGoal)))
  "Returns full string definition for message of type 'IncrementActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%IncrementGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: teleop_tools_msgs/IncrementGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32[] increment_by~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <IncrementActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <IncrementActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'IncrementActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
