; Auto-generated. Do not edit!


(cl:in-package teleop_tools_msgs-msg)


;//! \htmlinclude IncrementResult.msg.html

(cl:defclass <IncrementResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass IncrementResult (<IncrementResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <IncrementResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'IncrementResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name teleop_tools_msgs-msg:<IncrementResult> is deprecated: use teleop_tools_msgs-msg:IncrementResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <IncrementResult>) ostream)
  "Serializes a message object of type '<IncrementResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <IncrementResult>) istream)
  "Deserializes a message object of type '<IncrementResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<IncrementResult>)))
  "Returns string type for a message object of type '<IncrementResult>"
  "teleop_tools_msgs/IncrementResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'IncrementResult)))
  "Returns string type for a message object of type 'IncrementResult"
  "teleop_tools_msgs/IncrementResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<IncrementResult>)))
  "Returns md5sum for a message object of type '<IncrementResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'IncrementResult)))
  "Returns md5sum for a message object of type 'IncrementResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<IncrementResult>)))
  "Returns full string definition for message of type '<IncrementResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'IncrementResult)))
  "Returns full string definition for message of type 'IncrementResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <IncrementResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <IncrementResult>))
  "Converts a ROS message object to a list"
  (cl:list 'IncrementResult
))
